services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Content\Command\BuildCommand: ~

    Content\Builder\PageList: ~
    Content\Builder\Sitemap: ~

    Content\Decoder\MarkdownDecoder: ~
    Content\Decoder\YamlDecoder: ~

    Content\EventListener\Informator: ~
    Content\EventListener\SitemapListener: ~

    Content\Highlighter\Pygments: ~
    Content\Highlighter\Prism: ~

    Content\Decoder\HtmlDecoder:
        $highlighter: '@Content\Highlighter\Prism'

    Content\Service\Parsedown:
        $highlighter: '@Content\Highlighter\Prism'

    Content\PropertyHandler\DateTimePropertyHandler:
        tags:
            - { name: 'content.property_handler', property: 'date' }

    Content\PropertyHandler\LastModifiedPropertyHandler:
        tags:
            - { name: 'content.property_handler', property: 'lastModified' }

    Content\PropertyHandler\SlugPropertyHandler:
        tags:
            - { name: 'content.property_handler', property: 'slug' }

    Content\PropertyHandler\TitlesPropertyHandler:
        tags:
            - { name: 'content.property_handler', property: 'content' }

    # Decorators
    Content\Routing\UrlGenerator:
        decorates: Symfony\Component\Routing\Generator\UrlGeneratorInterface

    # Builder
    Content\Builder:
        public: true
        arguments:
            $public: "%kernel.project_dir%/public"
            $destination: "%kernel.project_dir%/build"

    # Content Manager
    Content\ContentManager:
        arguments:
            $path: '%kernel.project_dir%/data'
